package co.unicauca.justeat.client.presentation;

import co.unicauca.justeat.client.access.Factory;
import co.unicauca.justeat.client.access.IUserAccess;
import co.unicauca.justeat.client.domain.services.UserService;
import static co.unicauca.justeat.client.infra.Messages.successMessage;
import co.unicauca.justeat.commons.domain.User;

/**
 *
 * @author 
 *      SANTIAGO MUÑOZ 
 *      KEVIN ALARCON 
 *      JUAN JOSE LOPEZ 
 *      SANTIAGO CORDOBA 
 *      DANIEL MUÑOZ
 */

public class GUICreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form GUICreateAccount
     */
    public GUICreateAccount() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Create Account");
        TextPrompt textUserName = new TextPrompt("Enter a username", txtUserName);
        TextPrompt textPassword = new TextPrompt("Enter a Password", txtPassword);
        TextPrompt textName = new TextPrompt("Enter your name", txtName);
        TextPrompt textLastName = new TextPrompt("Enter your lastname", txtLastName);
        TextPrompt textIdNumber = new TextPrompt("Enter your ID Number", txtIdNumber);
        TextPrompt textCity = new TextPrompt("Enter a city", txtCity);
        TextPrompt textAddress = new TextPrompt("Enter a address", txtAddress);
        TextPrompt textPhone = new TextPrompt("Enter a phone number", txtPhone);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtUserName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txtLastName = new javax.swing.JTextField();
        txtIdNumber = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtCity = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtAddress = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        txtPhone = new javax.swing.JTextField();
        btnCreateAccount = new rsbuttom.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 260, -1));

        txtUserName.setForeground(new java.awt.Color(102, 102, 102));
        txtUserName.setBorder(null);
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 260, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 260, -1));

        txtName.setForeground(new java.awt.Color(102, 102, 102));
        txtName.setBorder(null);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 260, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 260, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 260, -1));

        txtLastName.setForeground(new java.awt.Color(102, 102, 102));
        txtLastName.setBorder(null);
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 260, 20));

        txtIdNumber.setForeground(new java.awt.Color(102, 102, 102));
        txtIdNumber.setBorder(null);
        jPanel1.add(txtIdNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 260, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 260, -1));

        txtCity.setForeground(new java.awt.Color(102, 102, 102));
        txtCity.setBorder(null);
        jPanel1.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 260, 20));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 260, -1));

        txtAddress.setForeground(new java.awt.Color(102, 102, 102));
        txtAddress.setBorder(null);
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 260, 20));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 260, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 260, -1));

        txtPhone.setForeground(new java.awt.Color(102, 102, 102));
        txtPhone.setBorder(null);
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 260, 20));

        btnCreateAccount.setBackground(new java.awt.Color(255, 66, 79));
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.setColorHover(new java.awt.Color(194, 18, 31));
        btnCreateAccount.setColorNormal(new java.awt.Color(255, 66, 79));
        btnCreateAccount.setColorPressed(new java.awt.Color(194, 18, 31));
        btnCreateAccount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 120, 30));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText(" Enter your personal details  to create an account");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 330, 30));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 50, 40));

        txtPassword.setBorder(null);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 260, 20));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        IUserAccess service = Factory.getInstance().getUserService();
        //Inyecta la dependencia

        UserService userService = new UserService(service);

        User user = new User();
        user.setUserName(txtUserName.getText());
        user.setUserContrasena(txtPassword.getText());
        user.setUserNombre(txtName.getText());
        user.setUserApellido(txtLastName.getText());
        user.setUserCedula(txtIdNumber.getText());
        user.setUserCiudad(txtCity.getText());
        user.setUserDireccion(txtAddress.getText());
        user.setUserCelular(txtPhone.getText());

        try {
            String response = userService.createUser(user);
            successMessage("Usuario " + response + " agregado con exito.", "Atención");
            clearCotronls();
            txtUserName.setText("");
        } catch (Exception ex) {
            System.out.println(ex);
            successMessage(ex.getMessage() + "Error", "Atención");

        }
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnCreateAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtIdNumber;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void clearCotronls() {
        txtName.setText("");
        txtPassword.setText("");
        txtName.setText("");
        txtLastName.setText("");
        txtIdNumber.setText("");
        txtCity.setText("");
        txtAddress.setText("");
        txtPhone.setText("");
    }
}
