package co.unicauca.justeat.client.presentation;

import co.unicauca.justeat.client.domain.User;
import static co.unicauca.justeat.client.infra.Messages.warningMessage;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.KeyEvent;

/**
 *
 * @author SANTIAGO MUÑOZ KEVIN ALARCON JUAN JOSE LOPEZ SANTIAGO CORDOBA DANIEL
 * MUÑOZ
 */
public class GUILoguin extends javax.swing.JFrame {

    /**
     * Creates new form GUILoguiin
     */
    public GUILoguin() {
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);

        TextPrompt textUser = new TextPrompt(" Enter you username", txtUser);
        TextPrompt textPass = new TextPrompt(" Enter you password", txtPassword);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        btnLoguin = new rsbuttom.RSButtonMetro();
        btnCreateAccount = new rsbuttom.RSButtonMetro();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAdmin = new rsbuttom.RSButtonMetro();
        btnDeliveryMan1 = new rsbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Welcome ! ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        txtUser.setBorder(null);
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 160, 20));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 190, 20));

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 190, 10));

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Universidad\\Lab-Software 2\\Just Eat\\Proyecto\\JustEat-Client\\src\\resources\\icons8_user_16.png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 20, 20));

        jLabel7.setBackground(new java.awt.Color(84, 84, 84));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Password:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 60, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Universidad\\Lab-Software 2\\Just Eat\\Proyecto\\JustEat-Client\\src\\resources\\icons8_password_16.png")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 20, 20));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Sign in your account");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        txtPassword.setBorder(null);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 160, 20));

        jLabel10.setBackground(new java.awt.Color(204, 204, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("User:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 50, 20));

        btnLoguin.setBackground(new java.awt.Color(255, 66, 79));
        btnLoguin.setText("Loguin");
        btnLoguin.setColorHover(new java.awt.Color(194, 18, 31));
        btnLoguin.setColorNormal(new java.awt.Color(255, 66, 79));
        btnLoguin.setColorPressed(new java.awt.Color(194, 18, 31));
        btnLoguin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLoguin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoguinActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoguin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 70, 30));

        btnCreateAccount.setBackground(new java.awt.Color(255, 255, 255));
        btnCreateAccount.setIcon(new javax.swing.ImageIcon("D:\\Universidad\\Lab-Software 2\\Just Eat\\Proyecto\\JustEat-Client\\src\\resources\\icons8_delivery_scooter_16.png")); // NOI18N
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.setColorHover(new java.awt.Color(255, 255, 255));
        btnCreateAccount.setColorNormal(new java.awt.Color(255, 255, 255));
        btnCreateAccount.setColorPressed(new java.awt.Color(255, 255, 255));
        btnCreateAccount.setColorTextHover(new java.awt.Color(255, 66, 79));
        btnCreateAccount.setColorTextNormal(new java.awt.Color(153, 153, 153));
        btnCreateAccount.setColorTextPressed(new java.awt.Color(255, 66, 79));
        btnCreateAccount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 110, 10));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 90, 10));

        jPanel3.setBackground(new java.awt.Color(255, 66, 79));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Universidad\\Lab-Software 2\\Just Eat\\Proyecto\\JustEat-Client\\src\\resources\\Just Eat.png")); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 122, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText(" Find your favorite restaurants and place your orders.");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 236, -1, -1));

        btnAdmin.setBackground(new java.awt.Color(255, 66, 79));
        btnAdmin.setIcon(new javax.swing.ImageIcon("D:\\Universidad\\Lab-Software 2\\Just Eat\\Proyecto\\JustEat-Client\\src\\resources\\icons8_administrator_male_16.png")); // NOI18N
        btnAdmin.setText("Admin");
        btnAdmin.setColorHover(new java.awt.Color(255, 66, 79));
        btnAdmin.setColorNormal(new java.awt.Color(255, 66, 79));
        btnAdmin.setColorPressed(new java.awt.Color(255, 66, 79));
        btnAdmin.setColorTextHover(new java.awt.Color(204, 204, 204));
        btnAdmin.setColorTextPressed(new java.awt.Color(204, 204, 204));
        btnAdmin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 120, 20));

        btnDeliveryMan1.setBackground(new java.awt.Color(255, 66, 79));
        btnDeliveryMan1.setIcon(new javax.swing.ImageIcon("D:\\Universidad\\Lab-Software 2\\Just Eat\\Proyecto\\JustEat-Client\\src\\resources\\icons8_delivery_scooter_16.png")); // NOI18N
        btnDeliveryMan1.setText("Delivery Man");
        btnDeliveryMan1.setColorHover(new java.awt.Color(255, 66, 79));
        btnDeliveryMan1.setColorNormal(new java.awt.Color(255, 66, 79));
        btnDeliveryMan1.setColorPressed(new java.awt.Color(255, 66, 79));
        btnDeliveryMan1.setColorTextHover(new java.awt.Color(204, 204, 204));
        btnDeliveryMan1.setColorTextPressed(new java.awt.Color(204, 204, 204));
        btnDeliveryMan1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel3.add(btnDeliveryMan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 130, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoguinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoguinActionPerformed
        

        //Aqui vendria el analizar si el usuario existe en el sistema
        if(txtUser.getText().equalsIgnoreCase("invitado")){
                    GUIPrincipal gp = new GUIPrincipal();
                    gp.setExtendedState(MAXIMIZED_BOTH);
                    gp.setVisible(true);
        }
        
        co.unicauca.justeat.client.infra.Security.usuario = new User(txtUser.getText(), txtPassword.getText(), "");
        
        if (true) {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    
                    
                    
                }
            });
            this.dispose();
        } else {
            warningMessage("Contraseña incorrecta", "Atención");
        }
                
    }//GEN-LAST:event_btnLoguinActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnLoguinActionPerformed(null);
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        GUICreateAccount gca = new GUICreateAccount();
        gca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILoguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILoguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILoguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILoguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               GUILoguin loguin = new GUILoguin();
               loguin.setVisible(true);
               loguin.setExtendedState(MAXIMIZED_BOTH);
               loguin.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnAdmin;
    private rsbuttom.RSButtonMetro btnCreateAccount;
    private rsbuttom.RSButtonMetro btnDeliveryMan1;
    private rsbuttom.RSButtonMetro btnLoguin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
