package co.unicauca.justeat.client.presentation;

import co.unicauca.justeat.client.access.Factory;
import co.unicauca.justeat.client.access.IRestaurantAccess;
import co.unicauca.justeat.client.domain.services.RestaurantService;
import static co.unicauca.justeat.client.infra.Messages.successMessage;
import co.unicauca.justeat.commons.domain.Restaurant;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SANTIAGO MUÑOZ 
 *         KEVIN ALARCON 
 *         JUAN JOSE LOPEZ 
 *         SANTIAGO CORDOBA 
 *         DANIEL MUÑOZ
 */

public class GUIPrincipalUser extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public GUIPrincipalUser() {
        initComponents();
        setLocationRelativeTo(null);
        TextPrompt textSearch = new TextPrompt(" Find restaurants near you", txtSearch);
        try {
            
        } catch (Exception ex) {
            Logger.getLogger(GUIPrincipalUser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblRest = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRestaurantes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnViewRest = new rsbuttom.RSButtonMetro();
        btnSearch1 = new rsbuttom.RSButtonMetro();
        btnBack = new rsbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(245, 243, 244));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Universidad\\Lab-Software 2\\Just Eat\\Proyecto\\JustEat-Client\\src\\main\\java\\resources\\search_26px.png")); // NOI18N

        txtSearch.setBorder(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 290, 40));
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));
        jPanel4.add(lblRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 240, 40));

        jTableRestaurantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ResID", "UserName", "NombreRes", "Direccion", "ciudad", "tematica"
            }
        ));
        jScrollPane1.setViewportView(jTableRestaurantes);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 780, 240));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Universidad\\Lab-Software 2\\Just Eat\\Proyecto\\JustEat-Client\\src\\main\\java\\resources\\just-eat-color.png")); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        btnViewRest.setBackground(new java.awt.Color(255, 66, 79));
        btnViewRest.setText("View Restaurant");
        btnViewRest.setColorHover(new java.awt.Color(194, 18, 31));
        btnViewRest.setColorNormal(new java.awt.Color(255, 66, 79));
        btnViewRest.setColorPressed(new java.awt.Color(194, 18, 31));
        btnViewRest.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRestActionPerformed(evt);
            }
        });
        jPanel4.add(btnViewRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 120, 30));

        btnSearch1.setBackground(new java.awt.Color(255, 66, 79));
        btnSearch1.setText("Search");
        btnSearch1.setColorHover(new java.awt.Color(194, 18, 31));
        btnSearch1.setColorNormal(new java.awt.Color(255, 66, 79));
        btnSearch1.setColorPressed(new java.awt.Color(194, 18, 31));
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 70, 40));

        btnBack.setText("Back");
        btnBack.setColorHover(new java.awt.Color(245, 243, 244));
        btnBack.setColorNormal(new java.awt.Color(245, 243, 244));
        btnBack.setColorPressed(new java.awt.Color(245, 243, 244));
        btnBack.setColorTextHover(new java.awt.Color(102, 102, 102));
        btnBack.setColorTextNormal(new java.awt.Color(255, 66, 79));
        btnBack.setColorTextPressed(new java.awt.Color(102, 102, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel4.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 50, 10));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -8, 840, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnViewRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRestActionPerformed
       try {
            llenarTabla();
        } catch (Exception ex) {
            Logger.getLogger(GUIPrincipalUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewRestActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        String nameRest = txtSearch.getText();

        IRestaurantAccess service = Factory.getInstance().getRestaurantService();

        RestaurantService restaurantService = new RestaurantService(service);

        Restaurant restaurant;
        try {
            restaurant = restaurantService.findRestaurant(nameRest);
        } catch (Exception e) {
            successMessage(e.getMessage(),"Atención");
            return;
        }
        txtSearch.setText("");
        showData(restaurant);
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       new GUIOpc().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipalUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnBack;
    private rsbuttom.RSButtonMetro btnSearch1;
    private rsbuttom.RSButtonMetro btnViewRest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableRestaurantes;
    private javax.swing.JLabel lblRest;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables


    private void showData(Restaurant restaurant) {
        JOptionPane.showMessageDialog(rootPane, restaurant.toString());
        lblRest.setText(restaurant.getResCiudad());
    }

    private void llenarTabla() throws Exception {
        IRestaurantAccess service = Factory.getInstance().getsRestaurantSerive();
        RestaurantService objRestaurantService = new RestaurantService(service);

        //Restaurant objRestaurant = new Restaurant();
        List<Restaurant> objListRestaurante = new ArrayList<Restaurant>();

        objListRestaurante = objRestaurantService.listRestaurant();

        String matriz[][] = new String[objListRestaurante.size()][6];

        for (int i = 0; i < objListRestaurante.size(); i++) {
            //matriz[i][0] = objListRestaurante.get(i).getResId();
            matriz[i][0] = objListRestaurante.get(i).getUserName();
            matriz[i][1] = objListRestaurante.get(i).getResNom();
            matriz[i][2] = objListRestaurante.get(i).getResDireccion();
            matriz[i][3] = objListRestaurante.get(i).getResCiudad();
            matriz[i][4] = objListRestaurante.get(i).getResTematicaComida();
        }

        jTableRestaurantes.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                     "UserName", "NombreRes", "Direccion", "ciudad", "tematica"
                }
        ));

    }
}
