package co.unicauca.justeat.client.presentation;

import co.unicauca.justeat.client.access.Factory;
import co.unicauca.justeat.client.access.IRestaurantAccess;
import co.unicauca.justeat.client.domain.services.RestaurantService;
import static co.unicauca.justeat.client.infra.Messages.successMessage;
import co.unicauca.justeat.commons.domain.Restaurant;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kevin Alarcón.
 */
public class GUIPrincipalUser extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public GUIPrincipalUser() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        TextPrompt textSearch = new TextPrompt(" Find restaurants near you", txtSearch);
        try {
            llenarTabla();
        } catch (Exception ex) {
            Logger.getLogger(GUIPrincipalUser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblRest = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRestaurantes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(new java.awt.Color(245, 243, 244));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        txtSearch.setBorder(null);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 290, 40));
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        lblRest.setText("jLabel2");
        jPanel4.add(lblRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jTableRestaurantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ResID", "UserName", "NombreRes", "Direccion", "ciudad", "tematica"
            }
        ));
        jScrollPane1.setViewportView(jTableRestaurantes);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 490, 240));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 294;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 2);
        getContentPane().add(jPanel4, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String nameRest = txtSearch.getText();

        IRestaurantAccess service = Factory.getInstance().getRestaurantService();

        RestaurantService restaurantService = new RestaurantService(service);

        Restaurant restaurant;
        try {
            restaurant = restaurantService.findRestaurant(nameRest);
        } catch (Exception e) {
            successMessage(e.getMessage(), "Atención");
            return;
        }
        txtSearch.setText("");
        showData(restaurant);
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipalUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableRestaurantes;
    private javax.swing.JLabel lblRest;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables


    private void showData(Restaurant restaurant) {
        lblRest.setText(restaurant.getResCiudad());
    }

    private void llenarTabla() throws Exception {
        IRestaurantAccess service = Factory.getInstance().getRestaurantService();
        RestaurantService objRestaurantService = new RestaurantService(service);

        //Restaurant objRestaurant = new Restaurant();
        List<Restaurant> objListRestaurante = new ArrayList<>();

        objListRestaurante = objRestaurantService.listRestaurant();

        String matriz[][] = new String[objListRestaurante.size()][6];

        for (int i = 0; i < objListRestaurante.size(); i++) {
            matriz[i][0] = objListRestaurante.get(i).getResId();
            matriz[i][1] = objListRestaurante.get(i).getUserName();
            matriz[i][2] = objListRestaurante.get(i).getResNom();
            matriz[i][3] = objListRestaurante.get(i).getResDireccion();
            matriz[i][4] = objListRestaurante.get(i).getResCiudad();
            matriz[i][5] = objListRestaurante.get(i).getResTematicaComida();
        }

        jTableRestaurantes.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "ResID", "UserName", "NombreRes", "Direccion", "ciudad", "tematica"
                }
        ));

    }
}
