package co.unicauca.justeat.client.presentation;

import static co.unicauca.justeat.client.infra.Messages.warningMessage;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author SANTIAGO MUÑOZ 
 *         KEVIN ALARCON 
 *         JUAN JOSE LOPEZ 
 *         SANTIAGO CORDOBA 
 *         DANIEL MUÑOZ
 */

public class GUIPrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipalAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        
//        Image icon = Toolkit.getDefaultToolkit().getImage("./src/resources/fondo.jpg");
//        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnExit = new rsbuttom.RSButtonMetro();
        rSButtonMetro4 = new rsbuttom.RSButtonMetro();
        rSButtonMetro5 = new rsbuttom.RSButtonMetro();
        rSButtonMetro6 = new rsbuttom.RSButtonMetro();
        btnNewRestaurant = new rsbuttom.RSButtonMetro();
        rSButtonMetro7 = new rsbuttom.RSButtonMetro();
        jpContainer = new javax.swing.JPanel();

        setExtendedState(6);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 66, 79));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setBackground(new java.awt.Color(255, 66, 79));
        btnExit.setText("Exit");
        btnExit.setColorHover(new java.awt.Color(255, 66, 79));
        btnExit.setColorNormal(new java.awt.Color(255, 66, 79));
        btnExit.setColorPressed(new java.awt.Color(255, 66, 79));
        btnExit.setColorTextHover(new java.awt.Color(204, 204, 204));
        btnExit.setColorTextPressed(new java.awt.Color(204, 204, 204));
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel3.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 200, 50));

        rSButtonMetro4.setText("Home");
        rSButtonMetro4.setColorHover(new java.awt.Color(255, 66, 79));
        rSButtonMetro4.setColorNormal(new java.awt.Color(255, 66, 79));
        rSButtonMetro4.setColorPressed(new java.awt.Color(255, 66, 79));
        rSButtonMetro4.setColorTextHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro4.setColorTextPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(rSButtonMetro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 40));

        rSButtonMetro5.setBackground(new java.awt.Color(255, 66, 79));
        rSButtonMetro5.setText("Create Menu");
        rSButtonMetro5.setColorHover(new java.awt.Color(255, 66, 79));
        rSButtonMetro5.setColorNormal(new java.awt.Color(255, 66, 79));
        rSButtonMetro5.setColorPressed(new java.awt.Color(255, 66, 79));
        rSButtonMetro5.setColorTextHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro5.setColorTextPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro5ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMetro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 200, 50));

        rSButtonMetro6.setBackground(new java.awt.Color(255, 66, 79));
        rSButtonMetro6.setText("Payment");
        rSButtonMetro6.setColorHover(new java.awt.Color(255, 66, 79));
        rSButtonMetro6.setColorNormal(new java.awt.Color(255, 66, 79));
        rSButtonMetro6.setColorPressed(new java.awt.Color(255, 66, 79));
        rSButtonMetro6.setColorTextHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro6.setColorTextPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro6ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMetro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 50));

        btnNewRestaurant.setBackground(new java.awt.Color(255, 66, 79));
        btnNewRestaurant.setText("New Restaurant");
        btnNewRestaurant.setColorHover(new java.awt.Color(255, 66, 79));
        btnNewRestaurant.setColorNormal(new java.awt.Color(255, 66, 79));
        btnNewRestaurant.setColorPressed(new java.awt.Color(255, 66, 79));
        btnNewRestaurant.setColorTextHover(new java.awt.Color(204, 204, 204));
        btnNewRestaurant.setColorTextPressed(new java.awt.Color(204, 204, 204));
        btnNewRestaurant.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNewRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRestaurantActionPerformed(evt);
            }
        });
        jPanel3.add(btnNewRestaurant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, 50));

        rSButtonMetro7.setBackground(new java.awt.Color(255, 66, 79));
        rSButtonMetro7.setText("Records");
        rSButtonMetro7.setColorHover(new java.awt.Color(255, 66, 79));
        rSButtonMetro7.setColorNormal(new java.awt.Color(255, 66, 79));
        rSButtonMetro7.setColorPressed(new java.awt.Color(255, 66, 79));
        rSButtonMetro7.setColorTextHover(new java.awt.Color(204, 204, 204));
        rSButtonMetro7.setColorTextPressed(new java.awt.Color(204, 204, 204));
        rSButtonMetro7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rSButtonMetro7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro7ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMetro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 200, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        jpContainer.setBackground(new java.awt.Color(255, 255, 255));
        jpContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jpContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 640, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRestaurantActionPerformed
        panelAddRestaurant paneAddRest = new panelAddRestaurant();
        paneAddRest.setSize(811,532);
        paneAddRest.setLocation(20,5);
        this.setTitle("Administrator");
        
        jpContainer.removeAll();
        jpContainer.add(paneAddRest, BorderLayout.CENTER);
        jpContainer.revalidate();
        jpContainer.repaint();
    }//GEN-LAST:event_btnNewRestaurantActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
      if(JOptionPane.showConfirmDialog(rootPane, "¿do you want to exit the program?", "Exit", JOptionPane.YES_OPTION) == JOptionPane.YES_OPTION){
        GUILoguin loguin = new GUILoguin();
        loguin.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_btnExitActionPerformed

    private void rSButtonMetro6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro6ActionPerformed
        warningMessage("En construcción....", "Atención");
    }//GEN-LAST:event_rSButtonMetro6ActionPerformed

    private void rSButtonMetro7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro7ActionPerformed
        warningMessage("En construcción....", "Atención");
    }//GEN-LAST:event_rSButtonMetro7ActionPerformed

    private void rSButtonMetro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro5ActionPerformed
       panelAddMenu panelAddMe= new panelAddMenu();
        panelAddMe.setSize(811,532);
        panelAddMe.setLocation(20,5);
        this.setTitle("Administrator");
        
        jpContainer.removeAll();
        jpContainer.add(panelAddMe, BorderLayout.CENTER);
        jpContainer.revalidate();
        jpContainer.repaint();
    }//GEN-LAST:event_rSButtonMetro5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnExit;
    private rsbuttom.RSButtonMetro btnNewRestaurant;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpContainer;
    private rsbuttom.RSButtonMetro rSButtonMetro4;
    private rsbuttom.RSButtonMetro rSButtonMetro5;
    private rsbuttom.RSButtonMetro rSButtonMetro6;
    private rsbuttom.RSButtonMetro rSButtonMetro7;
    // End of variables declaration//GEN-END:variables
}
