package co.unicauca.justeat.client.presentation;

import co.unicauca.justeat.client.access.Factory;
import co.unicauca.justeat.client.access.IRestaurantAccess;
import co.unicauca.justeat.client.domain.services.RestaurantService;
import static co.unicauca.justeat.client.infra.Messages.successMessage;
import co.unicauca.justeat.commons.domain.Restaurant;

/**
 *
 * @author SANTIAGO MUÑOZ 
 *         KEVIN ALARCON 
 *         JUAN JOSE LOPEZ 
 *         SANTIAGO CORDOBA 
 *         DANIEL MUÑOZ
 */
public class panelAddRestaurant extends javax.swing.JPanel {

    public panelAddRestaurant() {
        initComponents();
        TextPrompt textRestId = new TextPrompt(" Enter the restaurant id", txtRestId);
        TextPrompt textRestName = new TextPrompt(" Enter the restaurant name", txtRestName);
        TextPrompt textRestAddress = new TextPrompt(" Enter the restaurant address", txtRestAddress);
        TextPrompt textRestCity = new TextPrompt(" Enter the city of the restaurant.", txtRestCity);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRestId = new javax.swing.JTextField();
        txtRestName = new javax.swing.JTextField();
        txtRestAddress = new javax.swing.JTextField();
        txtRestCity = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnCreate = new rsbuttom.RSButtonMetro();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 66, 79));
        jLabel1.setText("Restaurant ID:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 130, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 66, 79));
        jLabel2.setText(" Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 80, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 66, 79));
        jLabel3.setText("Address:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 90, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 66, 79));
        jLabel4.setText("City:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 60, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 66, 79));
        jLabel5.setText("Category:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 80, -1));

        txtRestId.setBorder(null);
        add(txtRestId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 320, 30));

        txtRestName.setBorder(null);
        add(txtRestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 320, 30));

        txtRestAddress.setBorder(null);
        add(txtRestAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 320, 30));

        txtRestCity.setBorder(null);
        add(txtRestCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 320, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipico", "Parrilla", "Gourtmet", "Criollo", "Pollo" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 190, -1));

        jButton1.setText("Add");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 60, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("New Restaurant");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 160, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 320, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 320, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 320, 30));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 320, 30));

        btnCreate.setBackground(new java.awt.Color(255, 66, 79));
        btnCreate.setText("Create");
        btnCreate.setColorHover(new java.awt.Color(194, 18, 31));
        btnCreate.setColorNormal(new java.awt.Color(255, 66, 79));
        btnCreate.setColorPressed(new java.awt.Color(194, 18, 31));
        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 80, 30));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText(" Enter the details of the restaurant you want to register.");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 320, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Universidad\\Lab-Software 2\\Just Eat\\Proyecto\\JustEat-Client\\src\\resources\\img2.png")); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, -10, 230, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
         IRestaurantAccess service = Factory.getInstance().getRestaurantService();
        //Inyecta la dependencia

        RestaurantService restaurantService = new RestaurantService(service);

        Restaurant restaurant = new Restaurant();
        restaurant.setResId((txtRestId.getText()));
        restaurant.setUserName("Josman"); // Se valida con el loguin
        restaurant.setResNom(txtRestName.getText());
        restaurant.setResDireccion(txtRestAddress.getText());
        restaurant.setResCiudad(txtRestCity.getText());
        restaurant.setResTematicaComida("Pollo"); //Implementar con el combo box (debe poder seleccionar más de una opcion)

        try {
            String response = restaurantService.createRestaurant(restaurant);
            successMessage("Restaurante " + response + " agregado con exito.", "Atención");
            clearCotronls();
            txtRestId.setText("");
            //btnCreateRestaurant.setVisible(false);
        } catch (Exception ex) {
            System.out.println(ex);
            successMessage(ex.getMessage() + "Error", "Atención");

        }
    }//GEN-LAST:event_btnCreateActionPerformed
    
    private void clearCotronls() {
        txtRestId.setText("");
        txtRestName.setText("");
        txtRestAddress.setText("");
        txtRestCity.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnCreate;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtRestAddress;
    private javax.swing.JTextField txtRestCity;
    private javax.swing.JTextField txtRestId;
    private javax.swing.JTextField txtRestName;
    // End of variables declaration//GEN-END:variables
}
