package co.unicauca.justeat.client.presentation;

import co.unicauca.justeat.client.access.Factory;
import co.unicauca.justeat.client.access.IRestaurantAccess;
import co.unicauca.justeat.client.domain.services.RestaurantService;
import static co.unicauca.justeat.client.infra.Messages.successMessage;
import co.unicauca.justeat.commons.domain.Restaurant;

/**
 *
 * @author Kevin Alarcón
 */
public class panelAddRestaurant extends javax.swing.JPanel {

    public panelAddRestaurant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRestId = new javax.swing.JTextField();
        txtRestName = new javax.swing.JTextField();
        txtRestAddress = new javax.swing.JTextField();
        txtRestCity = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnCreate = new rsbuttom.RSButtonMetro();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 66, 79));
        jLabel1.setText("Restaurant ID:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 130, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 66, 79));
        jLabel2.setText(" Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 80, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 66, 79));
        jLabel3.setText("Address:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 90, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 66, 79));
        jLabel4.setText("City:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 60, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 66, 79));
        jLabel5.setText("Category:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 80, -1));

        txtRestId.setBorder(null);
        add(txtRestId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 320, 30));

        txtRestName.setBorder(null);
        add(txtRestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 320, 30));

        txtRestAddress.setBorder(null);
        add(txtRestAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 320, 30));

        txtRestCity.setBorder(null);
        add(txtRestCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 320, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipico", "Parrilla", "Gourtmet", "Criollo", "Pollo" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 190, -1));

        jButton1.setText("Add");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 60, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Registrer Restaurant");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 160, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 320, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 320, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 320, 30));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 320, 30));

        btnCreate.setBackground(new java.awt.Color(255, 66, 79));
        btnCreate.setText("Create");
        btnCreate.setColorHover(new java.awt.Color(194, 18, 31));
        btnCreate.setColorNormal(new java.awt.Color(255, 66, 79));
        btnCreate.setColorPressed(new java.awt.Color(194, 18, 31));
        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 80, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
         IRestaurantAccess service = Factory.getInstance().getRestaurantService();
        //Inyecta la dependencia

        RestaurantService restaurantService = new RestaurantService(service);

        Restaurant restaurant = new Restaurant();
        restaurant.setResId(Integer.parseInt(txtRestId.getText()));
        restaurant.setAdminId(1061782); // Se valida con el loguin
        restaurant.setResNom(txtRestName.getText());
        restaurant.setResDireccion(txtRestAddress.getText());
        restaurant.setResCiudad(txtRestCity.getText());
        restaurant.setResTematicaComida("Pollo"); //Implementar con el combo box (debe poder seleccionar más de una opcion)

        try {
            String response = restaurantService.createRestaurant(restaurant);
            successMessage("Restaurante " + response + " agregado con exito.", "Atención");
            clearCotronls();
            txtRestId.setText("");
            //btnCreateRestaurant.setVisible(false);
        } catch (Exception ex) {
            System.out.println(ex);
            successMessage(ex.getMessage() + "Error", "Atención");

        }
    }//GEN-LAST:event_btnCreateActionPerformed
    
    private void clearCotronls() {
        txtRestId.setText("");
        txtRestName.setText("");
        txtRestAddress.setText("");
        txtRestCity.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnCreate;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtRestAddress;
    private javax.swing.JTextField txtRestCity;
    private javax.swing.JTextField txtRestId;
    private javax.swing.JTextField txtRestName;
    // End of variables declaration//GEN-END:variables
}
